### ISSUE TITLE
Не добавляется новый webHook

### ISSUE THREAD

**Issue by spokik** [DenisNP/AliceHook#11]
Выбираю "Добавить вэбхук" => "Введите url вэбхука" => отправляю url =>"Отправила тестовый запрос на этот адрес. Что теперь?"

В вашем видео должно было появится поле с добавлением имени webhook, однако я не могу это воспроизвести. 

при этом тестовый хук исполняется
![image_2022-01-09_02-45-43](https://user-images.githubusercontent.com/61501832/148663973-e824a606-6f23-48f5-b6f5-64275c0fe603.png)

**Comment by DenisNP** [comment]
Да, ждём модерации от Яндекса после изменений настроек.

**Comment by DenisNP** [comment]
Модерация прошла, должно работать
